### ISSUE TITLE
Bug: IdScan ломает двери

### ISSUE THREAD

**Issue by StarRuCat** [ss220-space/Baystation12#293]
### Ckey

RuCat

### Описание бага

При отключении сканирования айди - шлюз просто перестает работать дистанционно.
![image](https://user-images.githubusercontent.com/27018085/180615543-2244717b-3f27-449f-9463-59d2f31d2223.png)

### Шаги воспроизведения

ИИ отключает IdScan и теряет возможность управлять шлюзом далее

### Ожидаемое поведение

Шлюз просто должен открываться даже людьми без доступа

### Операционная система

WIN 10

### Версия клиента

514

### Версия сервера

72029917f23b1f35186c324dbec5d594d41a7cc3 - master220 - 2022-07-20

### Идентификатор раунда

ci4-ccMU

**Comment by StarRuCat** [comment]
Чуток потестил - баг появляется в комнате бсд и телекоммах.

**Comment by YegorKandziuba** [comment]
> Чуток потестил - баг появляется в комнате бсд и телекоммах.

Дело в том, что это комнаты с платами secure airlock. При отключении IDScan эти комнаты становятся недоступными никому. Таков принцип работы этой платы.

В таком случае проси инженериков или инженерных этиков починить проводку.
