### ISSUE TITLE
Bug: малфом может стать любой игрок в начале раунда, даже не ии

### ISSUE THREAD

**Issue by keIgaras** [ss220-space/Baystation12#36]
### Ckey

keIgaras

### Описание бага

малфом может стать любой игрок в начале раунда, даже не ии, при этом его насильно закинет на роль ии даже если она у него не включена

### Шаги воспроизведения

Поставить в настройках персонажа напротив малфа "да"

### Ожидаемое поведение

Малфом может стать только человек который выбрал роль ии

### Операционная система

win 10

### Версия клиента

513.1542

### Версия сервера

Client Version: 513 Server Revision: 747e911 - master220 - 2021-07-08

### Идентификатор раунда

любой

**Comment by Honker9999999** [comment]
А где баг?

**Comment by botka4aet** [comment]
> А где баг?

Ты не хочешь играть за ИИ или не можешь(у тебя не наиграно часов для него)
Ты все равно играешь за ИИ

Где баг?

**Comment by Honker9999999** [comment]
> Ты не хочешь играть за ИИ или не можешь(у тебя не наиграно часов для него)
> Ты все равно играешь за ИИ
> 
> Где баг?

Ты выбираешь малфа, таким образом указывая что на ИИ ты все-таки хочешь(ибо малф). Это как выбрать культиста и потом говорить "А ПОЧЕМУ МНЕ ДАЛИ КУЛЬТИСТА???????"
Если часов не будет - тебе не дадут малфа. Там один параметр что и для ИИ.

Так что да, где баг?

**Comment by keIgaras** [comment]
> > Ты не хочешь играть за ИИ или не можешь(у тебя не наиграно часов для него)
> > Ты все равно играешь за ИИ
> > Где баг?
> 
> Ты выбираешь малфа, таким образом указывая что на ИИ ты все-таки хочешь(ибо малф). Это как выбрать культиста и потом говорить "А ПОЧЕМУ МНЕ ДАЛИ КУЛЬТИСТА???????"
> Если часов не будет - тебе не дадут малфа. Там один параметр что и для ИИ.
> 
> Так что да, где баг?

Проблема в том, что у нас нету системы часов, и основной онлайн идёт с парадиза а там нельзя быть малфом если ты не выбирал для игры ии, и получается что люди приходят и ставят себе малфа просто так, не думая что они им будут, и вместо какого-нибудь каргонца играют на малфе.

**Comment by keIgaras** [comment]
А где баг то?
нет бага

**Comment by Honker9999999** [comment]
> А где баг то?
> нет бага

Сделай предложение. Это не баг, но как предложение пойдет в принципе.
