### ISSUE TITLE
Bug: Пропадание спрайта Визора/Вуали для Таяр

### ISSUE THREAD

**Issue by Wastelander41** [ss220-space/Baystation12#41]
### Ckey

HumbleGuy

### Описание бага

Спрайты Вуали/Визора, по крайней мере с МедХУДом, пропадают если их отключить, появляются если включить.

### Шаги воспроизведения

Надеть визор/вуаль c медХудом, отключить ХУД.

### Ожидаемое поведение

Спрайт должен оставаться на месте, а не пропадать, таярам нельзя показывать свои глаза.

### Операционная система

Win10

### Версия клиента

513.1542

### Версия сервера

e3a1026e9998f090e374c27c3029e00142ba027e - master220 - 2021-07-09

### Идентификатор раунда

Любой

**Comment by Gaxeer** [comment]
Это не баг. Слот худа - это слот глаз, собственно тот же что и у вуали. А это значит ты носишь либо худ либо вуаль

**Comment by Wastelander41** [comment]
Наверное вы не так поняли, есть Визор и Вуаль с интегрированным худом, и
они отключаемые, при отключении спрайт становится прозрачным.

сб, 10 июл. 2021 г., 20:39 Gaxeer ***@***.***>:

**Comment by Bizzonium** [comment]
Да, там был коммент от Gaxeer, но он понял что ошибся и удалил его. Баг исправлен.

**Comment by Wastelander41** [comment]
Премного благодарен.

вс, 11 июл. 2021 г., 07:27 Aziz Chynaliev ***@***.***>:
