### ISSUE TITLE
Bug:Проблема с доступом

### ISSUE THREAD

**Issue by keIgaras** [ss220-space/Baystation12#48]
### Ckey

keIgaras

### Описание бага

У капитана нет доступа к двери в сауну из технических тоннелей, подозреваю что ни у кого его нет.

### Шаги воспроизведения

Попытаться открыть дверь в техи из сауны

### Ожидаемое поведение

Дверь открывается

### Операционная система

win 10

### Версия клиента

513.1542

### Версия сервера

Client Version: 513 Server Revision: 747e911 - master220 - 2021-07-08

### Идентификатор раунда

в любом раунде(честно просто не знал что это тут надо указывать)

**Comment by Honker9999999** [comment]
Дверь в сауну? Это какая? Кинь скрин, если можешь.

**Comment by keIgaras** [comment]
> Дверь в сауну? Это какая? Кинь скрин, если можешь.

Я ее не первый раз вижу, поэтому когда приду к компу скину скриншот, ну сам в коде проверю доступы

**Comment by keIgaras** [comment]
А где проблема?
А нет проблемы
