### ISSUE TITLE
Bug: Сломан хоткей хардсюита

### ISSUE THREAD

**Issue by keIgaras** [ss220-space/Baystation12#54]
### Ckey

keIgaras

### Описание бага

Сломаны хоткеи для модулей в Хмах, их нельзя использовать, всё из-за того что теперь на скм пинг

### Шаги воспроизведения

нажать скм чтобы достать модуль когда ты его выбрал

### Ожидаемое поведение

Модуль активируется

### Операционная система

win 10

### Версия клиента

513.1542

### Версия сервера

Client Version: 513 Server Revision: 747e911 - master220 - 2021-07-08

### Идентификатор раунда

в любом раунде(честно просто не знал что это тут надо указывать)

**Comment by Vallat** [comment]
Хоткеи для хардсьютов настраиваются в преференсах, СКМ был заменён на Альт+СКМ.
Так же, на выбор, есть еще комбинации Альт+Клик, Ктрл+Клик и Ктрл+Шифт+Клик
![image](https://user-images.githubusercontent.com/10997188/125421534-b896fad2-8642-4c39-a11e-8d39c48f5ac7.png)

**Comment by keIgaras** [comment]
А где поломка?
нет поломки
